engines:
  openai:
    api_key: "${OPENAI_API_KEY}"
    base_url: "${OPENAI_API_BASE_URL}"
    # base_url: "http://localhost:11434/v1"
#    api_key: "${OPENAI_API_KEY}"
#    base_url: "http://host.docker.internal:11434/v1"
  #   api_key: "${OPENAI_API_KEY}"
    # base_url: "https://api.openai.com/v1"

  # azure:
  #   - api_key: "${OPENAI_API_KEY}"
  #     base_url: "http://localhost:1234/v1"
  #     api_version: "2024-04-01-preview"

  gemini:
    enabled: true
    project_id: "encrypted-llm"

  bedrock:
    enabled: true
    region: us-east-1

# Database configuration (optional - will use DATABASE_URL env var if not specified)
database_url: "${DATABASE_URL}"

