FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w" -o /goop main.go


FROM public.ecr.aws/lambda/go:latest
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.1 /lambda-adapter /opt/extensions/lambda-adapter

ENV OPENAI_API_BASE_URL="https://api.openai.com/v1"
ENV VERTEX_AI_PROJECT_ID="encrypted-llm"

ENV PORT=8080
ENV AWS_LAMBDA_ADAPTER_LOG_LEVEL=DEBUG
ENV AWS_LAMBDA_ADAPTER_STRIP_STAGE_FROM_PATH=true
ENV AWS_LAMBDA_ADAPTER_ENABLE_STREAMING=true
ENV AWS_LWA_INVOKE_MODE=response_stream

EXPOSE 8080

COPY --from=builder /goop /var/task/
COPY config.yml /var/task/config.yml
CMD [ "goop" ]
