services:
  goop:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: goop-app
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://goop_user:goop_password@postgres:5432/goop?sslmode=disable
      - PORT=8080
    volumes:
      - .:/app
      - /app/bin
    depends_on:
      postgres:
        condition: service_healthy
    command: ["air", "-c", ".air.toml"]

  postgres:
    image: postgres:17-alpine
    container_name: goop-postgres
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_DB: goop
      POSTGRES_USER: goop_user
      POSTGRES_PASSWORD: goop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goop_user -d goop"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: goop-pgadmin
    restart: unless-stopped
    networks:
      - default
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@goop.local.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: goop-network
