AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GOOP API (Lambda Function URL + Supabase via DATABASE_URL secret)

Parameters:
  BedrockInferenceProfileArn:
    Type: String
    Default: '*'
    Description: Inference profile ARN your function will invoke.

Resources:
  ############################################################
  # Secrets: DATABASE_URL (you will set the value post-deploy)
  ############################################################
  DatabaseUrlSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: goop/db/database-url
      Description: "DATABASE_URL for Goop application - UPDATE THIS AFTER DEPLOYMENT"
      SecretString: |
        {
          "DATABASE_URL": "PLACEHOLDER_UPDATE_IN_CONSOLE"
        }

  ############################################################
  # IAM role for Lambda (minimal permissions)
  ############################################################
  GoopLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource:
                  - !Ref DatabaseUrlSecret
        - PolicyName: BedrockInvokeModelAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - !Ref BedrockInferenceProfileArn

  ############################################################
  # Lambda function (OUTSIDE VPC) with Function URL
  ############################################################
  GoopAPI:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 256
      Role: !GetAtt GoopLambdaExecutionRole.Arn
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: response_stream
          AWS_LWA_READINESS_CHECK_PROTOCOL: "tcp"
          PORT: "8080"
          DATABASE_URL: !Sub '{{resolve:secretsmanager:goop/db/database-url:SecretString:DATABASE_URL}}'
      FunctionUrlConfig:
        InvokeMode: RESPONSE_STREAM
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
            - POST
            - PUT
            - DELETE
          AllowHeaders:
            - 'Content-Type'
            - 'X-Amz-Date'
            - 'Authorization'
            - 'X-Api-Key'
            - 'X-Amz-Security-Token'
          MaxAge: 600
    Metadata:
      DockerTag: goop-lambda-image
      DockerContext: .
      Dockerfile: Dockerfile.lambda

Outputs:
  FunctionUrl:
    Description: "Lambda Function URL"
    Value: !GetAtt GoopAPIUrl.FunctionUrl
